# Generated by Django 4.2.6 on 2023-10-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='tag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
