# Generated by Django 4.2.6 on 2023-10-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(default='default.png', unique=True, upload_to='items_img'),
        ),
    ]
